### ISSUE TITLE
about Discord Rich Presence PLUGIN

### ISSUE THREAD

**Issue by steve02081504** [ponapalt/csaori#5]
@ponapalt 
As you know, I've just updated the Discord Rich Presence PLUGIN code to support saving the image key corresponding to the ghost name to `ImageTable.txt`

Then I'm wondering a couple of things:
* should we remove the design of `ImageTable.txt` and let ghost provide its own corresponding image key via a special event
* should we provide some generic images for ghost authors to customize their own ghost icons
  - or open a website or some other form to allow ghosts to upload their own ghost icons

**Comment by ponapalt** [comment]
Because I'm not using Discord, You may change code as you wish.
( I'm not good at real-time communication, such as chat communication platform. )

Note : please change application ID if you want to create new release, because current app ID is tied to my account.
It's parameter of Discord_Initialize function.

**Comment by steve02081504** [comment]
![图片](https://user-images.githubusercontent.com/31927825/139057899-95071de0-2bd5-4694-8512-fcd44d9bee3a.png)
![图片](https://user-images.githubusercontent.com/31927825/139057933-25955134-31e7-44d0-aa10-f6770e449080.png)

How do I update all this now?

**Comment by steve02081504** [comment]
[discord.zip](https://github.com/ponapalt/csaori/files/7425790/discord.zip)

**Comment by ponapalt** [comment]
I think it's a quirky but not bad idea to notify AppID. It's the only way to add images freely.

Anyway, I’ll leave it to you, because I have no motivation about Discord...

**Comment by steve02081504** [comment]
So could you please update the update source for this plugin?
I think it will provide more customization for most ghosts, but unfortunately I removed the old list of special ghosts with custom icons to simplify the code development, hope you don't mind
If you need to get these ghosts back to displaying properly on the discord, please use the `OnDiscordPluginCustomLargeImageKey`

**Comment by steve02081504** [comment]
`CompatibilityImageKeyTable` added
